#!/bin/bash

# This file does not work on Windows. You need:
#   - bash
#   - clang

# Load CLANG and OPT
source settings

FOLDER=examples
BCFOLDER=build/examples
FILE=hello

if [[ $# -gt 0 && "$1" = "--human" ]]; then
    HUMAN=1
    shift
fi

if [[ $# -eq 1 ]]; then
    FILE="$1"
fi

CFILE="$FOLDER/$FILE.c"
OFILE="$BCFOLDER/$FILE.bc"

# Print human-readable LLVM byte code to stdout
if [[ $HUMAN -eq 1 ]]; then
    if command -v highlight >/dev/null 2>&1; then
        CODE=$(highlight --stdout --out-format=truecolor $CFILE)
    else
        CODE=$(cat $CFILE)
    fi
    echo "-- BEGIN $CFILE ---------------------------"
    echo "$CODE"
    echo "-- END $CFILE -----------------------------"
    echo
    CMD="$CLANG -emit-llvm -S -c -o - $CFILE"
else # output binary bc to file
    mkdir -p $(dirname "$OFILE")
    CMD="$CLANG -emit-llvm -c -o $OFILE $CFILE"
fi

echo $CMD
echo
eval $CMD
