#!/bin/bash

# This file does not work on Windows. You need:
#   - bash
#   - clang

FOLDER=examples
FILE=hello

if [[ $# -eq 1 ]]; then
    FILE=$1
fi

CFILE="$FOLDER/$FILE.c"

# Print human-readable LLVM byte code to stdout
CLANG="clang -emit-llvm -S -o - $CFILE"

exec $CLANG
