#!/bin/bash

# use export OPT=/your/path/to/your/opt/installation/on/mac
# before running this file to point to a different opt binary
if [[ "$OPT" == "" ]]; then
    OPT=opt
fi

FOLDER=examples
FILE=hello

if [[ $# -gt 0 ]]; then
    FILE="$1"
fi

CFILE="$FOLDER/$FILE.c"
BCFILE="$FOLDER/$FILE.bc"

echo $CFILE
echo $BCFILE

# compile bitcode if it doesn't exist
if [[ ! -e $BCFILE || $CFILE -nt $BCFILE ]]; then
    echo "Compiling $CFILE..."
    ./emitbc $FILE
fi

CMD="$OPT -load build/nullderef/libNullDereferenceDetection.so -nullderef < $BCFILE > /dev/null"
echo $CMD

eval $CMD
