#!/bin/bash

# Load CLANG and OPT
source settings

FOLDER=examples
FILE=hello

if [[ $# -gt 0 ]]; then
    FILE="$1"
fi

CFILE="$FOLDER/$FILE.c"
BCFILE="$FOLDER/$FILE.bc"

# Recompile the LLVM pass C++ code, don't run clang if
# compilation failed.
make -C build || exit

# Compile bitcode if it doesn't exist or if its old
if [[ ! -e $BCFILE || $CFILE -nt $BCFILE ]]; then
    echo "Compiling $CFILE..."
    ./emitbc $FILE
fi

CMD="$OPT -load build/nullderef/libNullDereferenceDetection.so -nullderef < $BCFILE > /dev/null"

echo $CMD
eval $CMD
